### ISSUE TITLE
命令执行时出现未知错误

### ISSUE THREAD

**Issue by Mcayear** [Twiyin0/koishi-plugin-jryspro#2]
```
2023-07-12 11:07:24 [W] command 今日运势 
                        TypeError: Cannot read properties of undefined (reading 'fortuneSummary')
                            at _Command.<anonymous> (/koishi/node_modules/koishi-plugin-jryspro/lib/index.js:147:294)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1678:14)
                            at async _Command.execute (/koishi/node_modules/@koishijs/core/lib/index.cjs:1693:22)
                            at async /koishi/node_modules/@koishijs/core/lib/index.cjs:2307:22
                            at async _Session.withScope (/koishi/node_modules/@koishijs/core/lib/index.cjs:2175:22)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:871:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:871:16)
                            at async next (/koishi/node_modules/@koishijs/core/lib/index.cjs:871:16)
                            at async _Processor._handleMessage (/koishi/node_modules/@koishijs/core/lib/index.cjs:882:22)
```

**Comment by ChuYanSir** [comment]
这个我也遇到了

**Comment by Twiyin0** [comment]
这个是因为没有读取到 `用户id` 导致，koishi偶尔会读取不到个别用户的id，你可以手动在数据库内重新导入这个用户的信息

**Comment by Twiyin0** [comment]
已将该错误转为提示，后续可能会有相同的情况，检查一下能否正确读取用户id（数字），如果正常无法读取用户id可能是适配器问题。该issues就这样关闭吧如果有新的问题可以开新的提问
